### ISSUE TITLE
LH inventory

### ISSUE THREAD

**Issue by hdolinh** [NCEAS/learning-hub-organization#3]

**Comment by hdolinh** [comment]
- [ ] OSS deep dive
- [ ] organize materials for package

**Comment by camilavargasp** [comment]
- [Lesson on QA/QC](https://nceas.github.io/oss-lessons/data-munging-qa-qc-cleaning/data-munging-qa-qc-cleaning.html) (cleaning and wrangling II)

**Comment by camilavargasp** [comment]
We will track all LH lessons in [course-catalog](https://github.com/NCEAS/course-catalog) reporistory
