### ISSUE TITLE
Weekly + Monthly LH Meetings

### ISSUE THREAD

**Issue by hdolinh** [NCEAS/learning-hub-organization#5]
[Agenda + Meeting notes](https://docs.google.com/document/d/19v4nrBC44l22Ba7e5SQIWCvL4Xy1ot2pfLXJ2HNFvKA/edit?usp=sharing)

**Comment by hdolinh** [comment]
- [ ] 04/25/2023

**Comment by hdolinh** [comment]
Weekly update reminder

- [ ] 05/16/2023

**Comment by hdolinh** [comment]
Monthly Deep Dives

June

- [ ] Confirm topic
- [ ] Send out reminder

**Comment by camilavargasp** [comment]
This issue does not serve its purpose anymore. Relevant links will be on Project's README
