### ISSUE TITLE
Monthly UCSB RDC Meeting

### ISSUE THREAD

**Issue by hdolinh** [NCEAS/learning-hub-organization#65]
[Agenda + Meeting notes](https://docs.google.com/document/d/1xaW4C9j1ic1FRgh7nQgMMd4iH30ndSxd0y7mfCQri14/edit?usp=sharing)

**Comment by hdolinh** [comment]
2023 Meeting Lead
- [ ] May:
- [ ] June:
- [ ] July:
- [ ] August:
- [ ] September:
- [ ] October:
- [ ] November:
- [ ] December:

**Comment by camilavargasp** [comment]
Done for the year
